#Cleaning up medical patient records : Medical Insurance Project

## Working with Strings

1. The string `medical_data` stores the medical records for ten individuals. Each record is separated by a `;` and contains the name, age, BMI (body mass index), and insurance cost for an individual, in that order.
   

In [2]:
medical_data = \
"""Marina Allison   ,27   ,   31.1 , 
#7010.0   ;Markus Valdez   ,   30, 
22.4,   #4050.0 ;Connie Ballard ,43 
,   25.3 , #12060.0 ;Darnell Weber   
,   35   , 20.6   , #7500.0;
Sylvie Charles   ,22, 22.1 
,#3022.0   ;   Vinay Padilla,24,   
26.9 ,#4620.0 ;Meredith Santiago, 51   , 
29.3 ,#16330.0;   Andre Mccarty, 
19,22.7 , #2900.0 ; 
Lorena Hodson ,65, 33.1 , #19370.0; 
Isaac Vu ,34, 24.8,   #7045.0"""

print(medical_data)

Marina Allison   ,27   ,   31.1 , 
#7010.0   ;Markus Valdez   ,   30, 
22.4,   #4050.0 ;Connie Ballard ,43 
,   25.3 , #12060.0 ;Darnell Weber   
,   35   , 20.6   , #7500.0;
Sylvie Charles   ,22, 22.1 
,#3022.0   ;   Vinay Padilla,24,   
26.9 ,#4620.0 ;Meredith Santiago, 51   , 
29.3 ,#16330.0;   Andre Mccarty, 
19,22.7 , #2900.0 ; 
Lorena Hodson ,65, 33.1 , #19370.0; 
Isaac Vu ,34, 24.8,   #7045.0


2. First, I represented the insurance costs in US dollars.

   Replace all instances of `#` in `medical_data` with `$`. and stored the result in a variable called `updated_medical_data`.
   
   Print `updated_medical_data`.

In [3]:
updated_medical_data = medical_data.replace('#', '$')
print(updated_medical_data)

Marina Allison   ,27   ,   31.1 , 
$7010.0   ;Markus Valdez   ,   30, 
22.4,   $4050.0 ;Connie Ballard ,43 
,   25.3 , $12060.0 ;Darnell Weber   
,   35   , 20.6   , $7500.0;
Sylvie Charles   ,22, 22.1 
,$3022.0   ;   Vinay Padilla,24,   
26.9 ,$4620.0 ;Meredith Santiago, 51   , 
29.3 ,$16330.0;   Andre Mccarty, 
19,22.7 , $2900.0 ; 
Lorena Hodson ,65, 33.1 , $19370.0; 
Isaac Vu ,34, 24.8,   $7045.0


3. To calculate the number of medical records in our data.

   I Created a variable called `num_records` and initialized it at 0.

In [4]:
num_records = 0

4. Next, I wrote a `for` loop to iterate through the `updated_medical_data` string. Inside of the loop, add `1` to `num_records` when the current character is equal to `$`.

In [6]:
for char in updated_medical_data:
    if char == '$':
        num_records +=1
    

5. Outside of the loop, print `num_records` with the following message:

   ```
   There are {num_records} medical records in the data.
   ```

In [7]:
print("There are " + str(num_records)+ "medical records in the data.")

There are 10medical records in the data.


## Splitting Strings

6. The medical data in its current form is difficult to analyze. An essential job for a data scientist is to clean up data so that it's easy to work with.

   To split the `updated_medical_data` string into a list of each record as is separated by a `;` in the string and store the result in a variable called `medical_data_split` and print this variable.

In [8]:
medical_data_split = updated_medical_data.split(';')
print(medical_data_split)

['Marina Allison   ,27   ,   31.1 , \n$7010.0   ', 'Markus Valdez   ,   30, \n22.4,   $4050.0 ', 'Connie Ballard ,43 \n,   25.3 , $12060.0 ', 'Darnell Weber   \n,   35   , 20.6   , $7500.0', '\nSylvie Charles   ,22, 22.1 \n,$3022.0   ', '   Vinay Padilla,24,   \n26.9 ,$4620.0 ', 'Meredith Santiago, 51   , \n29.3 ,$16330.0', '   Andre Mccarty, \n19,22.7 , $2900.0 ', ' \nLorena Hodson ,65, 33.1 , $19370.0', ' \nIsaac Vu ,34, 24.8,   $7045.0']


7. The data is now stored in a list, but it is still hard to read. I therefore split each medical record into its own list.

   First, I defined an empty list called `medical_records`.

In [9]:
medical_records = []

8. Next, iterated through `medical_data_split` and for each record, split the string after each comma (`,`) and appended the split string to `medical_records`.

   Print `medical_records` after the loop.

In [10]:
for record in medical_data_split:
    medical_records.append(record.split(','))
print(medical_records)

[['Marina Allison   ', '27   ', '   31.1 ', ' \n$7010.0   '], ['Markus Valdez   ', '   30', ' \n22.4', '   $4050.0 '], ['Connie Ballard ', '43 \n', '   25.3 ', ' $12060.0 '], ['Darnell Weber   \n', '   35   ', ' 20.6   ', ' $7500.0'], ['\nSylvie Charles   ', '22', ' 22.1 \n', '$3022.0   '], ['   Vinay Padilla', '24', '   \n26.9 ', '$4620.0 '], ['Meredith Santiago', ' 51   ', ' \n29.3 ', '$16330.0'], ['   Andre Mccarty', ' \n19', '22.7 ', ' $2900.0 '], [' \nLorena Hodson ', '65', ' 33.1 ', ' $19370.0'], [' \nIsaac Vu ', '34', ' 24.8', '   $7045.0']]


## Cleaning Data

9. The data is now slightly more readable. However, it is not properly formatted - it contains unnecessary whitespace.

   To fix this, I started by creating an empty list called `medical_records_clean`.

In [11]:
medical_records_clean = []

10. Next, I used a `for` loop to iterate through `medical_records`.

    Inside of the loop, I created an empty list called `record_clean`. We'll use this list to store a formatted version of each medical record.

In [13]:
# for record in medical_records:
#     record_clean = []

11. After the `record_clean` variable, I created a nested `for` loop that goes through each `record`:

    ```py
    for item in record
    ```
    
    Inside of this loop, append `item.strip()` to `record_clean` to remove any whitespace from the string.

In [22]:
 for record in medical_records:
    record_clean = []
    for item in record:
        record_clean.append(item.strip())


12. Finally, I needed to add each cleaned up record to `medical_records_clean`.

    Outside of the nested `for` loop, I appended `record_clean` to `medical_records_clean`.

In [23]:
for record in medical_records:
    record_clean = []
    for item in record:
        record_clean.append(item.strip())
    medical_records_clean.append(record_clean)

13. To see the output, I Printed the `medical_records_clean` outside of the `for` loops.

    You should see output that is formatted and much easier to read.

In [24]:
print(medical_records_clean)

[['Isaac Vu', '34', '24.8', '$7045.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Darnell Weber', '35', '20.6', '$7500.0'], ['Sylvie Charles', '22', '22.1', '$3022.0'], ['Vinay Padilla', '24', '26.9', '$4620.0'], ['Meredith Santiago', '51', '29.3', '$16330.0'], ['Andre Mccarty', '19', '22.7', '$2900.0'], ['Lorena Hodson', '65', '33.1', '$19370.0'], ['Isaac Vu', '34', '24.8', '$7045.0']]


## Analyzing Data

14. The data is now clean and ready for analysis.

    For example, to print out the names of each of the ten individuals, we can use the following loop:
    ```py
    for record in medical_records_clean:
      print(record[0])
    ```
    
    Add this loop to the code block below and run it.

In [27]:

for record in medical_records_clean:
    print(record[0])

Isaac Vu
Marina Allison
Markus Valdez
Connie Ballard
Darnell Weber
Sylvie Charles
Vinay Padilla
Meredith Santiago
Andre Mccarty
Lorena Hodson
Isaac Vu


15. If I wanted all the names in the medical records to be uppercase characters.

    In the `for` loop, update `records[0]` before the `print` statement so that all of the characters are uppercase.
    
    Run the code to see the result.

In [30]:
for record in medical_records_clean:
    record[0]= record[0].upper()
    print(record[0])

ISAAC VU
MARINA ALLISON
MARKUS VALDEZ
CONNIE BALLARD
DARNELL WEBER
SYLVIE CHARLES
VINAY PADILLA
MEREDITH SANTIAGO
ANDRE MCCARTY
LORENA HODSON
ISAAC VU


16. To store each name, age, BMI, and insurance cost in separate lists.

    To start, create four empty lists:
    - `names`
    - `ages`
    - `bmis`
    - `insurance_costs`

In [32]:
names = []
ages= []
bmis = []
insurance_costs = []

17. Next, I iterated through `medical_records_clean` and for each record:
    - Append the name to `names`.
    - Append the age to `ages`.
    - Append the BMI to `bmis`.
    - Append the insurance cost to `insurance_costs`.

In [34]:
for record in medical_records_clean:
    names.append(record[0])
    ages.append(record[1])
    bmis.append(record[2])
    insurance_costs.append(record[3])

18. Print `names`, `ages`, `bmis`, and `insurance_costs` outside of the loop.

    Make sure the output is what you expect.

In [36]:
print(names)
print(ages)
print(bmis)
print(insurance_costs)

['ISAAC VU', 'ISAAC VU', 'MARINA ALLISON', 'MARKUS VALDEZ', 'CONNIE BALLARD', 'DARNELL WEBER', 'SYLVIE CHARLES', 'VINAY PADILLA', 'MEREDITH SANTIAGO', 'ANDRE MCCARTY', 'LORENA HODSON', 'ISAAC VU']
['34', '34', '27', '30', '43', '35', '22', '24', '51', '19', '65', '34']
['24.8', '24.8', '31.1', '22.4', '25.3', '20.6', '22.1', '26.9', '29.3', '22.7', '33.1', '24.8']
['$7045.0', '$7010.0', '$4050.0', '$12060.0', '$7500.0', '$3022.0', '$4620.0', '$16330.0', '$2900.0', '$19370.0', '$7045.0']


19. Now that all the data is in separate lists, we can easily perform analysis on that data. 
For instance, to  calculate the average BMI in our dataset.

    First, I created a variable called `total_bmi` and set it equal to 0.

In [38]:
total_bmi = 0

20. Next, I used a `for` loop to iterate through `bmis` and add each `bmi` to `total_bmi`.

   

In [45]:
for i in bmis:
    total_bmi += float(i)
print(total_bmi)

307.90000000000003


21. After the for loop, I created a variable called `average_bmi` that stores the `total_bmi` divided by the length of the `bmis` list then printed out `average_bmi` with the following message:
    ```
    Average BMI: {average_bmi}
    ```

In [46]:
average_bmi = total_bmi/len(bmis)
print("Average BMI:" + str(average_bmi))

Average BMI:25.658333333333335


## Extra

22. To Calculate the average insurance cost in `insurance_costs`. I had to the remove the `$` in order to calculate this.
    - Then finally wrote a for loop that outputs a string for each individual in the following format:
    ```
    Marina is 27 years old with a BMI of 31.1 and an insurance cost of $7010.0.
Markus is 30 years old with a BMI of 22.4 and an insurance cost of $4050.0.
    ...
    ...
    
  

In [52]:
updated_insurance_costs = []
for item in insurance_costs:
    updated_insurance_costs.append(item.strip('$'))
print(updated_insurance_costs)


['7045.0', '7010.0', '4050.0', '12060.0', '7500.0', '3022.0', '4620.0', '16330.0', '2900.0', '19370.0', '7045.0']


In [56]:
total_insurance_cost = 0
for i in updated_insurance_costs:
    total_insurance_cost += float(i)
print(total_insurance_cost)

90952.0


In [58]:
average_insurance_cost = total_insurance_cost/len(updated_insurance_costs)
print(average_insurance_cost)

8268.363636363636


In [59]:
for record in medical_records_clean:
    print(record[0] + 'is ' + record[1] + ' years old with a BMI of '+ record[2] + 'and an insurance cost of ' + record[3])

ISAAC VUis 34 years old with a BMI of 24.8and an insurance cost of$7045.0
MARINA ALLISONis 27 years old with a BMI of 31.1and an insurance cost of$7010.0
MARKUS VALDEZis 30 years old with a BMI of 22.4and an insurance cost of$4050.0
CONNIE BALLARDis 43 years old with a BMI of 25.3and an insurance cost of$12060.0
DARNELL WEBERis 35 years old with a BMI of 20.6and an insurance cost of$7500.0
SYLVIE CHARLESis 22 years old with a BMI of 22.1and an insurance cost of$3022.0
VINAY PADILLAis 24 years old with a BMI of 26.9and an insurance cost of$4620.0
MEREDITH SANTIAGOis 51 years old with a BMI of 29.3and an insurance cost of$16330.0
ANDRE MCCARTYis 19 years old with a BMI of 22.7and an insurance cost of$2900.0
LORENA HODSONis 65 years old with a BMI of 33.1and an insurance cost of$19370.0
ISAAC VUis 34 years old with a BMI of 24.8and an insurance cost of$7045.0
